version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - streamflow-backend

  redis:
    container_name: redis
    image: redis:6.0
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - streamflow-backend

volumes:
  postgres-data:
  redis_data:

networks: 
  streamflow-backend: